name: Generate and Commit Keystore

on:
  workflow_dispatch:

jobs:
  keystore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Clean old keystore
      run: rm -f app/release-keystore.jks release-keystore.jks.base64

    - name: Generate keystore
      run: |
        keytool -genkeypair -v \
          -keystore app/release-keystore.jks \
          -alias $KEYALIAS \
          -storepass $STOREPASSWORD \
          -keypass $KEYPASSWORD \
          -dname "CN=amrosolonline, OU=amrosolgithub, O=amrosolcommunity, L=jakarta, ST=jakarta, C=62" \
          -keyalg RSA -keysize 2048 -validity 10000
      env:
        STOREPASSWORD: ${{ secrets.STOREPASSWORD }}
        KEYALIAS: ${{ secrets.KEYALIAS }}
        KEYPASSWORD: ${{ secrets.KEYPASSWORD }}

    - name: Encode keystore to base64
      run: base64 app/release-keystore.jks > release-keystore.jks.base64

    - name: Upload keystore base64
      uses: actions/upload-artifact@v4
      with:
        name: release-keystore.jks.base64
        path: release-keystore.jks.base64

    - name: Commit keystore to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add app/release-keystore.jks
        git commit -m "Add release keystore" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
