name: Generate Release Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate keystore
      run: |
        keytool -genkeypair -v \
          -keystore release-keystore.jks \
          -alias myalias \
          -storepass amrosolsetia8 \
          -keypass amrosolsetia8 \
          -dname "CN=amrosolonline, OU=amrosolgithub, O=amrosolcommunity, L=jakarta, ST=jakarta, C=62" \
          -keyalg RSA -keysize 2048 -validity 10000

    - name: Encode keystore to base64
      run: base64 release-keystore.jks > release-keystore.jks.base64

    - name: Upload keystore base64
      uses: actions/upload-artifact@v4
      with:
        name: release-keystore.jks.base64
        path: release-keystore.jks.base64